name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

defaults:
  run:
      working-directory: ./firmware

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.2
    
